
DROP DATABASE IF EXISTS COURSE;
CREATE DATABASE COURSE;
USE COURSE;

DROP TABLE IF EXISTS `CLAZZ`;
CREATE TABLE `CLAZZ`(
	`ID` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '班级ID',
	`NAME` VARCHAR(255) DEFAULT NULL COMMENT '班级名字',
	`CREATETIME` VARCHAR(32) NOT NULL COMMENT '班级创建时间',
	`CREATER` INT(11) NOT NULL COMMENT '创建人的ID',
	`DESCRIPTION` VARCHAR(255) DEFAULT NULL COMMENT '描述',
	PRIMARY KEY  (`ID`)
)ENGINE=INNODB DEFAULT CHARSET=UTF8 COMMENT='班级数据表';
INSERT INTO `CLAZZ`(`ID`,`NAME`,`CREATETIME`,`CREATER`,`DESCRIPTION`)VALUES(1,'超级管理员',NOW(),1,'超级管理员组');

DROP TABLE IF EXISTS `USER`;
CREATE TABLE `USER`(
	`ID` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '用户ID',
	`CLASS_ID` INT(11) UNSIGNED NOT NULL COMMENT '班级ID',
	`NAME` VARCHAR(255) NOT NULL COMMENT '姓名',
	`USERNAME` VARCHAR(255) NOT NULL COMMENT '用户名',
	`PASSWORD` VARCHAR(255) NOT NULL COMMENT '密码',
	`SEX` ENUM('MALE','FEMALE') NOT NULL COMMENT'性别',
	`EMAIL` VARCHAR(255) DEFAULT NULL COMMENT '邮件',
	`TEL` VARCHAR(15) DEFAULT NULL COMMENT '邮件',
	`WENXIN` VARCHAR(255) DEFAULT NULL COMMENT '微信',
	`QQ` VARCHAR(255) DEFAULT NULL COMMENT 'QQ',
	`CREATETIME` VARCHAR(32) NOT NULL COMMENT '班级创建时间',
	`CREATER` INT(11) NOT NULL COMMENT '创建人的ID',
	PRIMARY KEY  (`ID`)
)ENGINE=INNODB DEFAULT CHARSET=UTF8 COMMENT='用户数据表';

INSERT INTO `USER`(`ID`,`CLASS_ID`,`NAME`,`USERNAME`,`PASSWORD`,`SEX`,`EMAIL`,`TEL`,`WENXIN`,`QQ`,`CREATETIME`,`CREATER`)
	VALUES(1,1,'初始化管理员','admin',MD5('123456'),'MALE','admin@163.com','','','',NOW(),1);
