
DROP DATABASE IF EXISTS course;
CREATE DATABASE course;
USE course;

DROP TABLE IF EXISTS `CLAZZ`;
CREATE TABLE `CLAZZ`(
	`ID` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '班级ID',
	`NAME` VARCHAR(255) DEFAULT NULL COMMENT '班级名字',
	`CREATETIME` VARCHAR(32) NOT NULL COMMENT '班级创建时间',
	`CREATER` INT(11) NOT NULL COMMENT '创建人的ID',
	`DESCRIPTION` VARCHAR(255) DEFAULT NULL COMMENT '描述',
	PRIMARY KEY  (`ID`)
)ENGINE=INNODB DEFAULT CHARSET=UTF8 COMMENT='班级数据表';

